language: cpp

dist: trusty
sudo: required

cache:
    apt: true   
   
   
compiler:
    - gcc
    - clang   
   
env:
    - TARGET=cpp
    - PYVERSION=2.6.9
    - PYVERSION=2.7.8
    - PYVERSION=3.2.6
    - PYVERSION=3.3.6
    - PYVERSION=3.4.3

before_install:
    # contains mostly new versions of gcc
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - echo "yes" | sudo add-apt-repository "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8 main" -y
    # this one contains python 2.6.9
    - if [ "$PYVERSION" = "2.6.9" ]; then sudo add-apt-repository ppa:fkrull/deadsnakes -y ; fi
    - sudo apt-get update -qq

install:
  - echo "== Install step =="
  - if [[ "$CC" == gcc* ]]; then sudo apt-get install -y --no-install-recommends gcc-6 g++-6 ; fi
  - if [[ "$CC" == clang* ]]; then sudo apt-get install -y --no-install-recommends clang-3.8 libc++-dev ; fi

script: 
  - if [[ "$CC" == gcc* ]]; then export CXX=g++-6 CC=gcc-6 ; fi
  - if [[ "$CC" == clang* ]]; then export CXXFLAGS="-stdlib=libc++" CXX=clang++-3.8 CC=clang-3.8 ; fi
  - if [ "$TARGET" = "cpp" ]; then sh travis/build_cpp.sh ; fi
  - if [ ! "$TARGET" = "cpp" ]; then cd pybindings ; fi
  - if [ ! "$TARGET" = "cpp" ] && [ "$PYVERSION" = "2.6.9" ]; then source ../travis/prepare_py26.sh ; fi
  - if [ ! "$TARGET" = "cpp" ] && [ ! "$PYVERSION" = "2.6.9" ]; then source ../travis/prepare_py.sh ; fi
  - if [ ! "$TARGET" = "cpp" ]; then sh ../travis/build_python.sh ; fi
  - if [ ! "$TARGET" = "cpp" ]; then sh ../travis/build_and_test_sdist.sh ; fi
