language: cpp
compiler:
    - gcc
    - clang

before_install:
    - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq
    - sudo apt-get install cmake

    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    # clang 3.4
    - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install libstdc++-4.8-dev; fi

  # clang 3.4
  #- if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  #- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script: 
  - $CXX --version
  - cmake . -G 'Unix Makefiles' 
  - make 
  - cd test 
  - make 
  - ./PlateTectonicsTests
  - cd ..
  - cd pybindings

  # Python 2.6 
  - source ~/virtualenv/python2.6/bin/activate
  - python --version
  - 'python setup.py clean build sdist develop && nosetests'
  - deactivate

  # Python 2.7
  - source ~/virtualenv/python2.6/bin/activate
  - python --version
  - 'python setup.py clean build sdist develop && nosetests'
  - deactivate'

  # Python 3.2
  - source ~/virtualenv/python2.6/bin/activate
  - python --version
  - 'python setup.py clean build sdist develop && nosetests'
  - deactivate  

  # Python 3.3
  - source ~/virtualenv/python2.6/bin/activate
  - python --version
  - 'python setup.py clean build sdist develop && nosetests'
  - deactivate

  # Python 3.4
  - source ~/virtualenv/python2.6/bin/activate
  - python --version
  - 'python setup.py clean build sdist develop && nosetests'
  - deactivate    
